"""empty message

Revision ID: 3f83fccd6542
Revises: 
Create Date: 2021-01-21 22:45:56.071225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f83fccd6542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('dept_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('dept_path', sa.String(length=255), nullable=True),
    sa.Column('dept_name', sa.String(length=128), nullable=True),
    sa.Column('sort', sa.BigInteger(), nullable=True),
    sa.Column('leader', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_index(op.f('ix_sys_dept_create_by'), 'sys_dept', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_dept_update_by'), 'sys_dept', ['update_by'], unique=False)
    op.create_table('sys_file_dir',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True, comment='目录名称'),
    sa.Column('p_id', sa.Integer(), nullable=True, comment='上级目录'),
    sa.Column('sort', sa.BigInteger(), nullable=True, comment='排序'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='路径'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_file_dir_create_by'), 'sys_file_dir', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_file_dir_update_by'), 'sys_file_dir', ['update_by'], unique=False)
    op.create_table('sys_file_info',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True, comment='类型'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称'),
    sa.Column('size', sa.Integer(), nullable=True, comment='大小'),
    sa.Column('p_id', sa.Integer(), nullable=True, comment='上级目录'),
    sa.Column('source', sa.String(length=255), nullable=True, comment='来源'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('full_url', sa.String(length=255), nullable=True, comment='全地址'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_file_info_create_by'), 'sys_file_info', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_file_info_update_by'), 'sys_file_info', ['update_by'], unique=False)
    op.create_table('sys_login_log',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True, comment='用户名'),
    sa.Column('status', sa.String(length=4), nullable=True, comment='状态'),
    sa.Column('ipaddr', sa.String(length=255), nullable=True, comment='ip地址'),
    sa.Column('login_location', sa.String(length=255), nullable=True, comment='归属地'),
    sa.Column('browser', sa.String(length=255), nullable=True, comment='浏览器'),
    sa.Column('os', sa.String(length=255), nullable=True, comment='系统'),
    sa.Column('platform', sa.String(length=255), nullable=True, comment='固件'),
    sa.Column('login_time', sa.DateTime(), nullable=True, comment='登录时间'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('msg', sa.String(length=255), nullable=True, comment='信息'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_login_log_create_by'), 'sys_login_log', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_login_log_update_by'), 'sys_login_log', ['update_by'], unique=False)
    op.create_table('sys_menu',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('paths', sa.String(length=128), nullable=True),
    sa.Column('menu_type', sa.String(length=1), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('permission', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.SmallInteger(), nullable=True),
    sa.Column('no_cache', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('breadcrumb', sa.String(length=255), nullable=True),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('sort', mysql.TINYINT(), nullable=True),
    sa.Column('visible', sa.String(length=1), nullable=True),
    sa.Column('is_frame', sa.String(length=1), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_sys_menu_create_by'), 'sys_menu', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_menu_update_by'), 'sys_menu', ['update_by'], unique=False)
    op.create_table('sys_opera_log',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True, comment='操作模块'),
    sa.Column('business_type', sa.String(length=128), nullable=True, comment='操作类型'),
    sa.Column('business_types', sa.String(length=128), nullable=True, comment='BusinessTypes'),
    sa.Column('method', sa.String(length=128), nullable=True, comment='函数'),
    sa.Column('request_method', sa.String(length=128), nullable=True, comment='请求方式'),
    sa.Column('operator_type', sa.String(length=128), nullable=True, comment='操作类型'),
    sa.Column('oper_name', sa.String(length=128), nullable=True, comment='操作者'),
    sa.Column('dept_name', sa.String(length=128), nullable=True, comment='部门名称'),
    sa.Column('oper_url', sa.String(length=255), nullable=True, comment='访问地址'),
    sa.Column('oper_ip', sa.String(length=128), nullable=True, comment='客户端ip'),
    sa.Column('oper_location', sa.String(length=128), nullable=True, comment='访问位置'),
    sa.Column('oper_param', sa.String(length=255), nullable=True, comment='请求参数'),
    sa.Column('status', sa.String(length=4), nullable=True, comment='操作状态'),
    sa.Column('oper_time', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.Column('json_result', sa.String(length=255), nullable=True, comment='返回数据'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('latency_time', sa.String(length=128), nullable=True, comment='耗时'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='ua'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_opera_log_create_by'), 'sys_opera_log', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_opera_log_update_by'), 'sys_opera_log', ['update_by'], unique=False)
    op.create_table('sys_post',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('post_name', sa.String(length=128), nullable=True),
    sa.Column('post_code', sa.String(length=128), nullable=True),
    sa.Column('sort', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=4), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_sys_post_create_by'), 'sys_post', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_post_update_by'), 'sys_post', ['update_by'], unique=False)
    op.create_table('sys_role',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('role_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=4), nullable=True),
    sa.Column('role_key', sa.String(length=128), nullable=True),
    sa.Column('role_sort', sa.BigInteger(), nullable=True),
    sa.Column('flag', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('admin', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('data_scope', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_sys_role_create_by'), 'sys_role', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_role_update_by'), 'sys_role', ['update_by'], unique=False)
    op.create_table('sys_role_dept',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('dept_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_role_dept_create_by'), 'sys_role_dept', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_role_dept_update_by'), 'sys_role_dept', ['update_by'], unique=False)
    op.create_table('sys_role_menu',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('menu_id', sa.BigInteger(), nullable=True),
    sa.Column('role_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_role_menu_create_by'), 'sys_role_menu', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_role_menu_update_by'), 'sys_role_menu', ['update_by'], unique=False)
    op.create_table('sys_setting',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('settings_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('settings_id')
    )
    op.create_index(op.f('ix_sys_setting_create_by'), 'sys_setting', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_setting_update_by'), 'sys_setting', ['update_by'], unique=False)
    op.create_table('sys_user',
    sa.Column('create_by', sa.BigInteger(), nullable=True, comment="'创建者'"),
    sa.Column('update_by', sa.BigInteger(), nullable=True, comment="'更新者'"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment="'创建时间'"),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment="'最后更新时间'"),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment="'删除时间'"),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('nick_name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('dept_id', sa.BigInteger(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_sys_user_create_by'), 'sys_user', ['create_by'], unique=False)
    op.create_index(op.f('ix_sys_user_update_by'), 'sys_user', ['update_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_update_by'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_create_by'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_setting_update_by'), table_name='sys_setting')
    op.drop_index(op.f('ix_sys_setting_create_by'), table_name='sys_setting')
    op.drop_table('sys_setting')
    op.drop_index(op.f('ix_sys_role_menu_update_by'), table_name='sys_role_menu')
    op.drop_index(op.f('ix_sys_role_menu_create_by'), table_name='sys_role_menu')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_role_dept_update_by'), table_name='sys_role_dept')
    op.drop_index(op.f('ix_sys_role_dept_create_by'), table_name='sys_role_dept')
    op.drop_table('sys_role_dept')
    op.drop_index(op.f('ix_sys_role_update_by'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_create_by'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_post_update_by'), table_name='sys_post')
    op.drop_index(op.f('ix_sys_post_create_by'), table_name='sys_post')
    op.drop_table('sys_post')
    op.drop_index(op.f('ix_sys_opera_log_update_by'), table_name='sys_opera_log')
    op.drop_index(op.f('ix_sys_opera_log_create_by'), table_name='sys_opera_log')
    op.drop_table('sys_opera_log')
    op.drop_index(op.f('ix_sys_menu_update_by'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_create_by'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_login_log_update_by'), table_name='sys_login_log')
    op.drop_index(op.f('ix_sys_login_log_create_by'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    op.drop_index(op.f('ix_sys_file_info_update_by'), table_name='sys_file_info')
    op.drop_index(op.f('ix_sys_file_info_create_by'), table_name='sys_file_info')
    op.drop_table('sys_file_info')
    op.drop_index(op.f('ix_sys_file_dir_update_by'), table_name='sys_file_dir')
    op.drop_index(op.f('ix_sys_file_dir_create_by'), table_name='sys_file_dir')
    op.drop_table('sys_file_dir')
    op.drop_index(op.f('ix_sys_dept_update_by'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_create_by'), table_name='sys_dept')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
