"""empty message

Revision ID: c5239d25f99c
Revises: 3f83fccd6542
Create Date: 2021-01-21 23:16:53.131686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5239d25f99c'
down_revision = '3f83fccd6542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_menu', sa.Column('status', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_menu', 'status')
    # ### end Alembic commands ###
